name: web_project
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.7
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  lints: ^4.0.0

flutter:
  uses-material-design: true
